export const productsList = [
  {
    id: 1,
    name: 'Nike Air Max',
    oldPrice: 300,
    price: 270,
    description: 'Comfortable and stylish running shoes.',
    image: '/products/product1.png',
  },
  {
    id: 2,
    name: 'Adidas Ultraboost',
    oldPrice: 250,
    price: 230,
    description: 'High-performance shoes with great cushioning.',
    image: '/products/product2.png',
  },
  {
    id: 3,
    name: 'Puma Suede Classic',
    oldPrice: 100,
    price: 90,
    description: 'Classic and trendy suede sneakers.',
    image: '/products/product3.png',
  },
  {
    id: 4,
    name: 'Reebok Nano X',
    oldPrice: 150,
    price: 140,
    description: 'Perfect shoes for cross-training.',
    image: '/products/product4.png',
  },
  {
    id: 5,
    name: 'New Balance 990',
    oldPrice: 200,
    price: 180,
    description: 'Versatile shoes for running and casual wear.',
    image: '/products/product5.png',
  },
  {
    id: 6,
    name: 'ASICS Gel-Kayano',
    oldPrice: 160,
    price: 150,
    description: 'Reliable shoes with excellent support.',
    image: '/products/product6.png',
  },
  {
    id: 7,
    name: 'Under Armour HOVR',
    oldPrice: 130,
    price: 120,
    description: 'Lightweight shoes with responsive cushioning.',
    image: '/products/product7.png',
  },
  {
    id: 8,
    name: 'Saucony Triumph',
    oldPrice: 170,
    price: 160,
    description: 'High-mileage running shoes with plush cushioning.',
    image: '/products/product8.png',
  },
  {
    id: 9,
    name: 'Brooks Ghost',
    oldPrice: 140,
    price: 130,
    description: 'Balanced and comfortable running shoes.',
    image: '/products/product9.png',
  },
  {
    id: 10,
    name: 'Mizuno Wave Rider',
    oldPrice: 150,
    price: 140,
    description: 'Smooth ride with great responsiveness.',
    image: '/products/product10.png',
  },
  {
    id: 11,
    name: 'Nike Pegasus',
    oldPrice: 120,
    price: 110,
    description: 'All-purpose running shoes with great fit.',
    image: '/products/product11.png',
  },
  {
    id: 12,
    name: 'Adidas Gazelle',
    oldPrice: 90,
    price: 80,
    description: 'Iconic shoes with timeless style.',
    image: '/products/product12.png',
  },
  {
    id: 13,
    name: 'Puma Future Rider',
    oldPrice: 110,
    price: 100,
    description: 'Retro-inspired shoes with modern comfort.',
    image: '/products/product13.png',
  },
  {
    id: 14,
    name: 'Reebok Classic Leather',
    oldPrice: 80,
    price: 70,
    description: 'Classic leather sneakers for everyday wear.',
    image: '/products/product14.png',
  },
  {
    id: 15,
    name: 'New Balance Fresh Foam',
    oldPrice: 130,
    price: 120,
    description: 'Soft and cushioned running shoes.',
    image: '/products/product15.png',
  },
  {
    id: 16,
    name: 'ASICS Nimbus',
    oldPrice: 160,
    price: 150,
    description: 'Premium running shoes with maximum cushioning.',
    image: '/products/product16.png',
  },
  {
    id: 17,
    name: 'Under Armour Charged',
    oldPrice: 110,
    price: 100,
    description: 'Responsive and durable running shoes.',
    image: '/products/product17.png',
  },
  {
    id: 18,
    name: 'Saucony Kinvara',
    oldPrice: 120,
    price: 110,
    description: 'Lightweight and fast running shoes.',
    image: '/products/product18.png',
  },
  {
    id: 19,
    name: 'Brooks Adrenaline',
    oldPrice: 150,
    price: 140,
    description: 'Supportive shoes for overpronation.',
    image: '/products/product19.png',
  },
  {
    id: 20,
    name: 'Mizuno Inspire',
    oldPrice: 140,
    price: 130,
    description: 'Stable shoes with great comfort.',
    image: '/products/product20.png',
  },
];
